/* Hand-written roast lines. Each thing gets one line picked by its key, so it stays the same on every screen. */
const ROASTS = {
  any: [
    "{name} has the survival instincts of a moth at a bonfire.",
    "Somewhere a golden retriever just felt smarter than {name}.",
    "{name} had one brain cell today and it called in sick.",
    "{name}'s brain is running on airplane mode.",
    "If confidence was IQ, {name} would be a genius. Tragic.",
    "Scientists are studying {name}. Not in a good way.",
    "{name} is the reason shampoo has instructions.",
    "Even autocorrect couldn't fix {name}'s decisions today.",
    "{name} out here playing life on easy mode and still losing.",
    "{name} is not the main character. {name} is the tutorial.",
    "{name}'s last thought left a voicemail. Nobody called back.",
    "{name} has the energy of a dog that just saw a door open.",
    "NASA called. They want to study the empty space in {name}'s head.",
    "{name} would lose a staring contest to a parked car.",
    "{name}'s brain has two tabs open and both are loading.",
    "{name} is proof that evolution takes breaks.",
    "If {name} was a spice, it would be flour.",
    "{name} brings nothing to the table and still asks for seconds.",
    "Somebody unplug {name} and plug him back in.",
    "{name} has the strategic mind of a Roomba.",
    "{name}'s search history is just \"how\".",
    "{name} could get lost in a hallway with one door.",
    "{name} is built different. Specifically, worse.",
    "Loading {name}'s common sense… 2%… error.",
    "{name} is running on vibes and a single granola bar.",
    "{name} peaked in kindergarten and it's been downhill since nap time.",
    "{name}'s guardian angel just requested a transfer.",
    "{name} reads the terms and conditions and still doesn't get it.",
    "Respectfully, {name} is a walking group chat screenshot.",
    "{name} thinks critical thinking is a type of workout.",
  ],
  nom: [
    "{name} is not on trial. {name} is the evidence.",
    "Honestly? {name} looked at this charge and said \"fair.\"",
    "The prosecution rests. So does {name}'s last thought.",
    "{name} didn't just do it. {name} committed to the bit with zero awareness.",
    "Charges filed. {name}'s lawyer already blocked his number.",
    "Nobody had to make this up. {name} just did it.",
    "This charge sheet is longer than {name}'s attention span.",
    "{name} pleads not guilty. The evidence pleads otherwise.",
    "Judge took one look at {name} and closed the case.",
    "{name} woke up and chose to be a headline.",
  ],
  moment: [
    "This photo should be in a museum. The Museum of Bad Decisions.",
    "Frame this. Show it at {name}'s wedding.",
    "Zoom in. You can see the thought leaving {name}'s head.",
    "{name} woke up and chose chaos. Chaos said \"no thanks.\"",
    "Caught in 4K. No lawyer can save {name} now.",
    "{name}'s mom is getting this one printed.",
    "This is {name}'s villain origin story, but dumber.",
    "Evidence exhibit A. And B. And C. It's all {name}.",
    "Somebody check on {name}. Actually, don't. This is funnier.",
    "This picture has more going on than {name}'s brain.",
    "National Geographic would pay for this {name} footage.",
    "{name} looks like he's buffering.",
  ],
  quote: [
    "{name} said this out loud. On purpose.",
    "Put it on a t-shirt. Make {name} pay for the first one.",
    "Philosophers wept. Not because it was deep.",
    "{name} speaks fluent nonsense and we're all bilingual now.",
    "That's not a quote, that's a cry for help from {name}'s last brain cell.",
    "Socrates who? We have {name}.",
    "{name} thought about this for zero seconds and it shows.",
    "The words are English. The logic is not.",
    "Every teacher {name} ever had just felt a chill.",
    "{name} should be legally required to think before speaking.",
    "Quote of the century. Unfortunately.",
  ],
  appeal: [
    "{name} is appealing? Bold move for someone with no defense.",
    "Objection: {name}'s whole personality.",
    "{name}'s lawyer just quit. Not even mad.",
    "This defense has the structural integrity of wet cardboard.",
    "{name} pleading innocent is the himmest thing {name} did today.",
    "The jury is laughing. That's not a good sign, {name}.",
    "{name} brought a spoon to a sword fight and called it a defense.",
    "Even {name} doesn't believe this one.",
  ],
  crown: [
    "All hail {name}, ruler of nothing, champion of vibes.",
    "{name} earned this crown the only way he knows how: by accident.",
    "The people have spoken, and they said {name}. Loudly.",
    "{name} is the Himmest. Nobody is surprised.",
    "Crown fits perfectly. It's the only thing in {name}'s head.",
    "History will remember this day. {name} will forget it by lunch.",
    "Long live King {name}. Short live his brain cells.",
    "{name} finally won something. It's this.",
  ],
  week: [
    "Another week, another collective IQ drop. Proud of you, boys.",
    "This week's highlights would get you all banned from a library.",
    "Seven days. Zero thoughts. Incredible consistency.",
    "If this group was a company, it would be bankrupt and somehow on fire.",
    "Scientists say brains peak at 25. You all peaked early.",
    "Somehow this week was dumber than last week. Growth.",
    "Not one of you thought before acting this week. Legendary.",
  ],
};
function roastLine(kind, name, key){
  let x = 2166136261;
  for (const c of String(key)) { x ^= c.charCodeAt(0); x = Math.imul(x, 16777619) >>> 0; }
  const own = ROASTS[kind] || [], pool = (x & 1) && own.length ? own : own.concat(ROASTS.any);
  return pool[(x >>> 1) % pool.length].replaceAll("{name}", name || "This guy");
}
